### ISSUE TITLE
Update installation instructions

### ISSUE THREAD

**Issue by chauncey-garrett** [Zettt/km-markdown-library#36]
There is no KM library file in the latest release or in the current repo. The install instructions in [README Download.md](https://github.com/Zettt/km-markdown-library/blob/75ffeb625a56120699c3d6daaba10368a2d1ef1b/README%20Download.md) need to be updated.

**Comment by Zettt** [comment]
Just checked, this is not true. What version are you using?

**Comment by chauncey-garrett** [comment]
v2.2 was the release I downloaded.

I see the `*.kmmacros` files and was able to install the macro set by opening each individual file but I do not see anything ending in `*.kmlibrary` in the either current Github repo on the master branch or from the latest release.

Perhaps I'm missing it. Could you link to the file?

**Comment by Zettt** [comment]
@chauncey-garrett I'm so sorry for the *very* late reply! To be frank, I haven't intended for my answer to take so long because I didn't anticipate the release of `v2.3` to take so long. That said 2.3 is now pending release and you can download it from the main GitHub page. Please come back tomorrow and I hopefully am able to make the process easier for you.

To update, I agree, it's not very straight forward. The easiest thing you can do at the moment is:

* delete old version entirely
* install new version

I plan to make this easier, but the Keyboard Maestro's AppleScript dictionary is not really helping me a lot with this. I regularly investigate whether the update can be made easier, but right now I can't.

**Comment by chauncey-garrett** [comment]
@Zettt Thanks for getting back to me! I checked out the new release but there is still no `*.kmlibrary` file.

Again, I can install by opening each macro *individually* but I cannot easily do so using the missing `*.kmlibrary` file that would include the entire macro set. See screenshot below:

![2015-04-03 at 11 18](https://cloud.githubusercontent.com/assets/302358/6984947/b3fd9e1a-d9f3-11e4-9c4b-1eff65c7d140.png)

**Comment by Zettt** [comment]
@chauncey-garrett I think you misunderstand GitHub a bit. When you at the main page of this repository there is a big section labelled "Download". http://cl.ly/image/3s1D2u3k3a0I

**Comment by chauncey-garrett** [comment]
@Zettt The miscommunication here is related to the fact that there are two separate and distinct releases:

1. [A download link using Box](https://app.box.com/s/cjch3nu8zzpc32m4gtp9ij794m3cllf7) which includes the library file
2. [The release channel on Github](https://github.com/Zettt/km-markdown-library/releases) which does not

I originally downloaded this repo via the release channel. Since a release channel is available, I assumed that the library file would be included within the repo and not elsewhere (via an external link). That is why I couldn't find the `.kmlibrary` file mentioned in the text of the above image—it doesn't exist within the repo! No misunderstanding of Github here.

Since I suspect I'm not the only one who would first download this repo either via the release channel, the "Download Zip" button, or a `git clone`, I think there are at least two things you can do to make this less confusing, take 'em or leave 'em:

- Include the library file in the repo
- Attach the files included in the Box download link as a "binary" under your releases

![2015-04-04 at 15 35](https://cloud.githubusercontent.com/assets/302358/6994468/6c7f80a6-dae0-11e4-8e65-89162e4ca24b.png)

Hope that helps clear up everything!

**Comment by Zettt** [comment]
I make it short. No.
