### ISSUE TITLE
Remove affiliate tag option

### ISSUE THREAD

**Issue by Zettt** [Zettt/km-markdown-library#41]
It's not useful, I think. I also don't have any conversion come in from this, so I think it would be safe to remove. 

I'd like to hear if anyone from the community tells me reasons not to. Otherwise it'll be removed in about a week or so. What's your opinion @pslobo, @pattulus, @philgruneich?

**Comment by philgruneich** [comment]
0 or 1 cent or 100 dollars, it is yours. I make very little from my AL, but every revenue stream comes together and the site sustains itself (soon sponsored posts). Perhaps what you really want is a little traction.

**Comment by Zettt** [comment]
Why would I need traction? I don't earn any money from this, nor do I intend to. This is clearly stated throughout the various macros. It also doesn't answer the question that I asked. Is this something people use or want? If not, I'll remove it.

**Comment by philgruneich** [comment]
I think I read this question in the wrong context then, at first I thought this was about the ethics in affiliate linking or something. I blame the lack of coffee.

I think that's something people want. In my case I use [Affiliate](https://itunes.apple.com/us/app/affiliate/id789724698?mt=12) and [StretchLink](http://stretchlinkapp.com/) to always set my affiliate credentials, so in my personal use case you can remove the option from the library, but I suppose it will be missed by someone.

There's also [SearchLink](http://brettterpstra.com/projects/searchlink/), so it's up to find out what the other kids are using these days.

**Comment by pattulus** [comment]
Options are always good – so ultimately I'd keep it because every Maestro out there wants something different. I'm in the same camp als Phillip (Affiliate, StrechtLink and SearchLink). In case you want it all lean and clean, drop it.

**Comment by Zettt** [comment]
@pattulus Thanks for the feedback. In that case we're 2 vs. 1. I'm more inclined to remove this piece of garbage that I have to carry around with every release.

**Comment by Zettt** [comment]
@philgruneich That's my point. I think it doesn't matter because the tools that are available are so much better than what I do. I knew that I can't come close to any of the specific apps but now that I've implemented the feature, I see that it adds a lot of weight and is unnecessary.

**Comment by Zettt** [comment]
Removed as of commit 582c415d06eafe48f30dfa3a759ac6e98d067ea4. Please also delete its variable from Keyboard Maestro. The name was `MMD__Add Affiliate Tags`
